// THIS TEST WAS GENERATED AUTOMATICALLY ON Thu Feb 04 2016 14:15:38 GMT+0200 (EET)

'use strict';

import chai from 'chai';
import {ValidationError} from '../../../lib/Resource/Exception/ValidationError';

// @todo: Add more advanced tests
suite('Resource/Exception/ValidationError', function() {
  test('Class ValidationError exists in Resource/Exception/ValidationError', () => {
    chai.expect(ValidationError).to.be.an('function');
  });
});
